name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: github-pages
      #     path: main.pdf
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
